### ISSUE TITLE
Colour scheme for theme_nottshc()

### ISSUE THREAD

**Issue by ChrisBeeley** [CDU-data-science-team/nottshcMethods#9]
There is currently no colour scheme defined in theme_nottshc() which results in a graph that looks like this 
![image](https://user-images.githubusercontent.com/1259867/117860118-d6435c80-b287-11eb-817d-cd2648e5e61c.png)

Could we please have something more attractive and accessible?

**Comment by Lextuga007** [comment]
I think we will need 2 colour schemes for bar charts because often we can use one colour but in cases like this one, where there are grouped ages by categories we need good definition as well as good colours. Viridis is a good palette for definition and is particularly good for graded colours. 

The other thing we may want to consider are the Trust's branding colours.

**Comment by ChrisBeeley** [comment]
I like the idea of Trust branded colours, can we investigate that?

**Comment by Lextuga007** [comment]
Although we haven't agreed on a colour scheme as such, I think we've moved along with having a couple of plot themes that will cover this in other issues/code so closing this particular issue.
